### ISSUE TITLE
Is 10 cams the maximum quantity I can control at the same time?

### ISSUE THREAD

**Issue by hellolwt** [sepp89117/GoPro_Web_RC#1]
Hello, me again.
Recently I tested it on Hero 10 Blacks, and I can't connect more than 10 cams at the same time.
Is 10 cams the maximum quantity I can control at the same time?

**Comment by sepp89117** [comment]
Hi,
in my code there is no limit.
The limit is determined by the hardware used.
I can find various topics about this on the web.
Under Windows there should probably be a maximum of 7 devices that can be connected at the same time.

Which hardware with which operating system do you use? 

[https://www.google.com/search?q=How+many+devices+can+be+connected+to+PC+Bluetooth+at+a+time](url)

**Comment by hellolwt** [comment]
I use Windows10 on PC, you're right, I can pair 10 devices and control only 7.

**Comment by sepp89117** [comment]
The latest Bluetooth 5 specification allows up to 7 device connections simultaneously to a primary device in active mode. 😔
I'm wondering if there's a way to control more cameras. But I don't have much hope.

**Comment by sepp89117** [comment]
I have now read that BLE has no limitation. In this case, the limitation is due to the hardware used. Can you try it with other devices?

**Comment by hellolwt** [comment]
> I have now read that BLE has no limitation. In this case, the limitation is due to the hardware used. Can you try it with other devices?

Seems you're right! I tested it on my android phone and it did work with 14 cams at the same time! Didn't work on my pc and laptop though. I will try more devices later.

**Comment by hellolwt** [comment]
Sorry that I don't have more device. 14 cams with my Android phone tested successfully.

**Comment by sepp89117** [comment]
If it is important to you to use it with the PC, you can test it with another operating system. You could run this live from a USB stick without touching your hard drive.
Either you take Ubuntu and install the Chrome browser after the start or you test Chrome OS.
[Ubuntu](https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview) 
[Chrome OS ](https://www.makeuseof.com/tag/download-google-chrome-os-and-run-on-a-real-computer/)

**Comment by hellolwt** [comment]
> If it is important to you to use it with the PC, you can test it with another operating system. You could run this live from a USB stick without touching your hard drive.
> Either you take Ubuntu and install the Chrome browser after the start or you test Chrome OS.
> [Ubuntu](https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview) 
> [Chrome OS ](https://www.makeuseof.com/tag/download-google-chrome-os-and-run-on-a-real-computer/) 

Not at all, using smart phone is ok. Thank you for your help!

**Comment by hellolwt** [comment]
I saw you update your code yesterday, now I have problem in connecting my cams, can you fix that? Thanks!

**Comment by sepp89117** [comment]
How are the problems expressed?

**Comment by hellolwt** [comment]
![微信图2234839](https://user-images.githubusercontent.com/78248878/207090230-5ad012fa-c37f-4697-be1d-392f7b9fed51.jpg)
I tried to reset it but didn't work.

**Comment by sepp89117** [comment]
I reverted the changes. On the PC it works without any problems

**Comment by hellolwt** [comment]
appreciate!

**Comment by sepp89117** [comment]
Please fork this repository. You can then test my changes in this repository and apply the commits to your fork if necessary.

**Comment by hellolwt** [comment]
ok.

**Comment by sepp89117** [comment]
Hi @hellolwt 
i released a android app:
https://github.com/sepp89117/GoEasyPro_Android

Do you want to test it?

**Comment by hellolwt** [comment]
> Hi @hellolwt i released a android app: https://github.com/sepp89117/GoEasyPro_Android
> 
> Do you want to test it?

How to use it?

**Comment by sepp89117** [comment]
> How to use it?

Please take a look at the readme. I updated it.
Best regards

**Comment by hellolwt** [comment]
It works successfully on Xiaomi Redmi K50 (Android 12). An amazing app! Quite convenient, thanks for sharing!

**Comment by sepp89117** [comment]
That's nice to hear! You're welcome
