### ISSUE TITLE
Authentication canceled x2 then Authentication failed.

### ISSUE THREAD

**Issue by Akxe** [sepp89117/GoPro_Web_RC#2]
Hi, I am getting an error:

```
GoPro_Web_RC.html:1 Uncaught (in promise) DOMException: Authentication canceled.
Promise.then (async)
(anonymous) @ GoPro_Web_RC.html:622
GoPro_Web_RC.html:1 Uncaught (in promise) DOMException: Authentication canceled.
Promise.then (async)
(anonymous) @ GoPro_Web_RC.html:610
GoPro_Web_RC.html:1 Uncaught (in promise) DOMException: Authentication failed.
Promise.then (async)
(anonymous) @ GoPro_Web_RC.html:634
```

I am using GoPro 10.

**Comment by sepp89117** [comment]
Hi, these are NetworkErrors, which occur when trying to start notifications. 

The pairing with the camera is probably wrong. 
Please pair the camera again using "Connect to GoPro App".
In rare cases during testing it was necessary to reset the connections in the camera.

**Comment by Akxe** [comment]
It did work better but failed anyway. It did, however, show some information before disconnecting.

PS: I did even try to clear all connections. Again it did help a but. I still got the errors, but is stayed connected. I could not however control anything at all :/

<details><summary>Console log</summary>
<pre>
GoPro_Web_RC.html:482 Connecting to 'GoPro 5309'.
GoPro_Web_RC.html:511 GATT connected
GoPro_Web_RC.html:531 Getting Services...
GoPro_Web_RC.html:550 Got control Service
GoPro_Web_RC.html:551 Getting control Characteristics...
GoPro_Web_RC.html:560 Got defInfo Service
GoPro_Web_RC.html:561 Getting model_number_string Characteristic...
GoPro_Web_RC.html:565 Got battInfo Service
GoPro_Web_RC.html:566 Getting battLevel Characteristic...
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 0
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 0
GoPro_Web_RC.html:698 27. 5. 2023 21:30:08 [readValue] 00002a19-0000-1000-8000-00805f9b34fb
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 32
GoPro_Web_RC.html:698 27. 5. 2023 21:30:08 [readValue] 00002a24-0000-1000-8000-00805f9b34fb
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 38
GoPro_Web_RC.html:719 > Model is Hero 10 Black
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 0
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 1
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 0
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 0
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 1
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:673 27. 5. 2023 21:30:08 [bufferExecNext] Last execution millis = 0
GoPro_Web_RC.html:596 Got Characteristic
GoPro_Web_RC.html:1 Uncaught (in promise) DOMException: Authentication canceled.
Promise.then (async)
(anonymous) @ GoPro_Web_RC.html:622
GoPro_Web_RC.html:1 Uncaught (in promise) DOMException: Authentication canceled.
Promise.then (async)
(anonymous) @ GoPro_Web_RC.html:610
GoPro_Web_RC.html:1 Uncaught (in promise) DOMException: Authentication failed.
Promise.then (async)
(anonymous) @ GoPro_Web_RC.html:634
GoPro_Web_RC.html:793 27. 5. 2023 21:33:27 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:27 [bufferExecNext] Last execution millis = 5
GoPro_Web_RC.html:793 27. 5. 2023 21:33:29 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:29 [bufferExecNext] Last execution millis = 5
GoPro_Web_RC.html:793 27. 5. 2023 21:33:30 [sendQueryToSingle] 2,19,54
GoPro_Web_RC.html:673 27. 5. 2023 21:33:30 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:793 27. 5. 2023 21:33:31 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:31 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:698 27. 5. 2023 21:33:33 [readValue] 00002a19-0000-1000-8000-00805f9b34fb
GoPro_Web_RC.html:673 27. 5. 2023 21:33:33 [bufferExecNext] Last execution millis = 110
GoPro_Web_RC.html:793 27. 5. 2023 21:33:34 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:34 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:793 27. 5. 2023 21:33:36 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:36 [bufferExecNext] Last execution millis = 2
GoPro_Web_RC.html:793 27. 5. 2023 21:33:37 [sendQueryToSingle] 2,19,54
GoPro_Web_RC.html:673 27. 5. 2023 21:33:37 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:793 27. 5. 2023 21:33:38 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:38 [bufferExecNext] Last execution millis = 2
GoPro_Web_RC.html:793 27. 5. 2023 21:33:40 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:40 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:793 27. 5. 2023 21:33:42 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:42 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:698 27. 5. 2023 21:33:43 [readValue] 00002a19-0000-1000-8000-00805f9b34fb
GoPro_Web_RC.html:673 27. 5. 2023 21:33:43 [bufferExecNext] Last execution millis = 71
GoPro_Web_RC.html:793 27. 5. 2023 21:33:44 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:44 [bufferExecNext] Last execution millis = 2
GoPro_Web_RC.html:793 27. 5. 2023 21:33:44 [sendQueryToSingle] 2,19,54
GoPro_Web_RC.html:673 27. 5. 2023 21:33:44 [bufferExecNext] Last execution millis = 2
GoPro_Web_RC.html:793 27. 5. 2023 21:33:46 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:46 [bufferExecNext] Last execution millis = 5
GoPro_Web_RC.html:793 27. 5. 2023 21:33:48 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:48 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:793 27. 5. 2023 21:33:50 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:50 [bufferExecNext] Last execution millis = 6
GoPro_Web_RC.html:793 27. 5. 2023 21:33:51 [sendQueryToSingle] 2,19,54
GoPro_Web_RC.html:673 27. 5. 2023 21:33:51 [bufferExecNext] Last execution millis = 2
GoPro_Web_RC.html:793 27. 5. 2023 21:33:53 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:53 [bufferExecNext] Last execution millis = 3
GoPro_Web_RC.html:698 27. 5. 2023 21:33:53 [readValue] 00002a19-0000-1000-8000-00805f9b34fb
GoPro_Web_RC.html:673 27. 5. 2023 21:33:53 [bufferExecNext] Last execution millis = 90
GoPro_Web_RC.html:793 27. 5. 2023 21:33:55 [sendQueryToSingle] 2,19,97
GoPro_Web_RC.html:673 27. 5. 2023 21:33:55 [bufferExecNext] Last execution millis = 6
</pre>
</details>

**Comment by sepp89117** [comment]
The GoPro doesn't seem to accept the connection. Pairing does not appear to complete correctly. 
Is the GoPro firmware up to date? 
When paired, does the GoPro report that the pairing was successful?

**Comment by Akxe** [comment]
The pairing does not complete on the GoPro screen. The GoPro is up-to-date.

**Comment by sepp89117** [comment]
Are you performing the pairing as described in the readme? 
You have to initiate a new connection with remote control in the camera and pair it with the Bluetooth manager of your smartphone or PC. When the devices are paired with each other, you can use this program. 
Do you use an Android smartphone?

**Comment by Akxe** [comment]
I did not. It did not occur to me. Even more so since the BT device picker shows the GoPro as connected...

**Comment by sepp89117** [comment]
The Web Bluetooth API is not mature. That's why I froze the development of this project. If you use an Android device, I recommend GoEasyPro_Android. 
https://github.com/sepp89117/GoEasyPro_Android

**Comment by Akxe** [comment]
I was trying to use this in a web app we have internally developed. But it is much harder than anticipated 😕

I will give it more thoughts tomorrow. Thanks for the hints though 😊

**Comment by sepp89117** [comment]
If your web app is open source, I might be able to give you some help. 
Communication with the cameras in GoEasyPro_Android is also significantly improved compared to this web app.
