### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by CreoKinetics** [sepp89117/GoPro_Web_RC#3]
Hi, I can't see any other way to contact you; this isn't an issue; I just wanted to discuss your project with you and see if you could help me with something.

Many thanks,

Jon

**Comment by sepp89117** [comment]
Hi Jon,
feel free to tell me your problem. Maybe I can help.

Best,
Sebastian

**Comment by CreoKinetics** [comment]
Hi Sebastian,

Thanks for getting back to me, it's not a problem, I wanted to discuss with
you if you were interested in doing some paid development work for me, I'm
after almost exactly what you've been building, if your interested I would
love to discuss paying you for your programming skills if possible

***@***.***

Many thanks,

Jon

**Comment by sepp89117** [comment]
Hi Jon,

You can contact me via gmail.com. My account name there is the same as here.

Best,
Sebastian
